### ISSUE TITLE
Impossible to enter string list values.

### ISSUE THREAD

**Issue by sergio-nsk** [Wirena/clang-format-configurator-v2#14]
![image](https://user-images.githubusercontent.com/18064360/224575874-18644073-0605-439f-8d79-13316b120f02.png)
How to enter string list items? The first button adds another button that can only be deleted.

**Comment by Wirena** [comment]
Grey plus button creates an empty array, which overrides BasedOnStyle default array
Blue plus button appends new element to the array, result looks like this:
![image](https://user-images.githubusercontent.com/62119056/224674045-4f9016f7-4267-45d4-a5d7-9a976b5031b6.png)

**Comment by sergio-nsk** [comment]
@Wirena  It does not for me. X is not red and no input fields are above X.

**Comment by Wirena** [comment]
> @Wirena It does not for me. X is not red and there are no input fields are above X.

Which clang-format version is set?

**Comment by sergio-nsk** [comment]
I don set it, just open https://clang-format-configurator.site/, clang-format-15 is a default version, then scroll to any +, for example `AttributeMacros`, and press +. The result is like in the issue description.

**Comment by Wirena** [comment]
@sergio-nsk I couldnt reproduce this problem, you do press blue plus button after the grey one?

![optionSelection](https://user-images.githubusercontent.com/62119056/226195652-ce619860-7f52-461f-b396-7ed6747ba28f.gif)

**Comment by sergio-nsk** [comment]
So, I have to press [ + ] twice to get it working. It's very non-obvious use case.

**Comment by Wirena** [comment]
@sergio-nsk 
Fixed it in [2d8bfac](https://github.com/Wirena/clang-format-configurator-v2/commit/2d8bfac4d60c7686233c86aed54c8e7afd0308a2). Initially I thought that there's a difference in how clang-format interprets empty array options and undefined options, but I was wrong, so having button to create empty array does not make sence
