### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by lukasz-mitka** [Wirena/clang-format-configurator-v2#22]
Since you don't have discussion enabled on this repo I'll use this issue, hope you don't mind.

Thank you for creating and maintaining this project!

**Comment by sergio-nsk** [comment]
Is the site down?

**Comment by Wirena** [comment]
@sergio-nsk yep, I run it on a very cheap VM with 0.5 GB RAM, and it looks like it hangs sometimes due to OOM(or so i think). I've made a cron job to reboot it every week, but looks like its not enough when under load

**Comment by Wirena** [comment]
@lukasz-mitka Thanks a lot for your appreciation, I'll keep trying to make it better

**Comment by sergio-nsk** [comment]
Why don't your host the site on GH Pages https://pages.github.com/? I think it will work well in GH Pages.

**Comment by Wirena** [comment]
@sergio-nsk I have backend running clang-format binary to format code on the right side and show changes, GH Pages won't help with this
