### ISSUE TITLE
What code should be changed if I changed the clang-format version?

### ISSUE THREAD

**Issue by tonyho** [Wirena/clang-format-configurator-v2#37]
Hi I have a problem when running this project locally if I changed the clang-format version, following is my steps:

I built the server and front-end with the following commands:

```
cd server
bash debug-script.sh -b

cd front-end
npm install
npm run build
sudo npm install -g serve


```

I deleted other clang-format versions in config.json, only keep the 17, and rename the 17.0.6 to 17.0.4, then, I run the server with:

```
./bin/clang-format-configurator 
INFO[0000] Configuration:
BindAddr: 0.0.0.0:8080
LogLevel: debug
CertFile: 
PKeyFile:  
INFO[0000] ./third-party/clang-format/clang-format-17.0.4 --version output:
clang-format version 17.0.4 
INFO[0000] Staring HTTP server      
```

Run the front end with:

```
serve -s build
```

Other options are kept by default.

When I open the front-end from web-broswer with url( http://IP:3000), it give s error: 

```
Something went wrong:
TypeError: Failed to fetch
```

From the broswer console, I can find a error :

```
POST http://localhost:8080/format?version=17.0.6&filext=.cpp net::ERR_CONNECTION_REFUSED
```

It seems it still post to the 17.0.6,not the 17.0.4, How Can I modify it?

**Comment by Wirena** [comment]
@tonyho There are two config.json files: `front-end/config.json` (soft link to `llvm/config.json`), and `server/config.json`. The first one is used exclusively by front end to display both available clang-format versions and options info, such as titles, defaults, etc, the second one is used exclusively by server. Looks like you modified only the second config, so front end still thinks there's 17.0.6 version, not the 17.0.4. Either manually rename version in `front-end/config.json` file or change required version list in [here](https://github.com/Wirena/clang-format-configurator-v2/blob/master/llvm/prepare.sh#L146) and rerun prepare.sh script

Btw, by the look of an error text in a web browser and console log, it seems like there's another problem with fetch, server should be responding with BadRequest status and "Selected version is not available" message, not refusing connection. Haven't run the server in http mode for a while, so i can't say if this is some bug with CORS or a problem on your side. I'll check it this week.

**Comment by tonyho** [comment]
> @tonyho There are two config.json files: `front-end/config.json` (soft link to `llvm/config.json`), and `server/config.json`. The first one is used exclusively by front end to display both available clang-format versions and options info, such as titles, defaults, etc, the second one is used exclusively by server. Looks like you modified only the second config, so front end still thinks there's 17.0.6 version, not the 17.0.4. Either manually rename version in `front-end/config.json` file or change required version list in [here](https://github.com/Wirena/clang-format-configurator-v2/blob/master/llvm/prepare.sh#L146) and rerun prepare.sh script↳
> 
> Btw, by the look of an error text in a web browser and console log, it seems like there's another problem with fetch, server should be responding with BadRequest status and "Selected version is not available" message, not refusing connection. Haven't run the server in http mode for a while, so i can't tell if this is some bug with CORS or a problem on your side. I'll check it this week.↳

Thanks, I figured it out that the url in frontend config.json should be adjusted to the IP of the server backend IP instead of localhost.
Now it is working.
