### ISSUE TITLE
Using diff mode with custom code doesn't work

### ISSUE THREAD

**Issue by lmb** [Wirena/clang-format-configurator-v2#39]
Hi, and thanks for your project. It looks really useful! I want to use it to find a style that matches the current coding conventions as closely as possible. For that I paste some of your code into the tab, and then switch to "diff" mode. I don't get any output unfortunately, the editor window is reset to empty.

Tested on Firefox and Chromium.

**Comment by Wirena** [comment]
@lmb thanks, yep, can confirm, I broke diff mode somehow :D. I'll fix it when I have some free time.
As for finding style to match some coding convention, try this project: https://github.com/alandefreitas/clang-unformat

**Comment by lmb** [comment]
that link made my day. thanks!
