### ISSUE TITLE
Public site times out

### ISSUE THREAD

**Issue by detly** [Wirena/clang-format-configurator-v2#51]
Visiting https://clang-format-configurator.site/ on 6/8/2024 times out (Firefox 128.0.3 via Snap in Ubuntu 24.04).

(Please don't consider this as any kind of pressure, it's just sometimes these things fall over for trivial reasons and we don't notice until someone tells us.)

**Comment by Wirena** [comment]
@detly thanks, fixed it

> Please don't consider this as any kind of pressure
That's Ok, thanks a lot for letting me know
