### ISSUE TITLE
IndentPPDirectives inconsistency between site and practical use on drive

### ISSUE THREAD

**Issue by ericwomer** [Wirena/clang-format-configurator-v2#58]
When enabling IndentPPDriectives in the configuration site it indents the #ifndef #define #endif block but on disk all # after #ifndef are indented until the last #endif

Desired behavior with IndentPPDirective without AfterHash (AfterHash just adds the indent after the hash for every PP declarative)
```c++
#ifndef HEADER_HPP_
#define HEADER_HPP_

#include <iostream>

#ifdef DEBUG
    #include <some_debug_include>
#endif

~~~

#endif // HEADER_HPP_H
``` 

Actual behavior without AfterHash
```c++
#ifndef HEADER_HPP_
#define HEADER_HPP_

    #include <iostream>

    #ifdef DEBUG
        #include <some_debug_include>
    #endif

~~~

#endif // HEADER_HPP_H
```

**Comment by Wirena** [comment]
@ericwomer Hi, could you send me your .clang-format file and tell which version you are using?

**Comment by ericwomer** [comment]
clang-format version:
`clang-format version 19.1.0 (Fedora 19.1.0-1.fc41)`

[Here](https://gist.github.com/ericwomer/3a37972e0604c878bd4b4e01c0205a79) is the .clang-format with duplicates removed and [here](https://gist.github.com/ericwomer/fad61184312188624a18af47b2be1c80) is the .clang-format as is from your site.

My [system info](https://gist.github.com/ericwomer/3a423531bb759a9ee85932071edc1c29) in case you want this also.

**Comment by Wirena** [comment]
@ericwomer 
Hi, I can't reproduce your "Actual behavior without AfterHash" case both locally with clang-format version 19.1.0 (tagged llvmorg-19.1.0) compiled from LLVM repo, and on the website.

I've played a bit with different clang-format versions and configs and I never got clang-format to indent PP directives inside header guard #ifndef. The closest result I was able to get is this:

```
 #ifndef HEADER_HPP_        <--- different defines
    #define HEADER_OTHER

    #include <iostream>

    #ifdef DEBUG
        #include <some_debug_include>
    #endif

class A {};

#endif  // HEADER_HPP_H
```

Can you double-check it and test with clang-format version 18.X.X, if possible?

**Comment by ericwomer** [comment]
@Wirena Found out whats causing the issue, don't know if its intended or not, but it has to do with // (or any text) after the last `#endif` statement

With text (comment) after the last `#endif` statement
```c++
#ifndef HEADER_HPP_
    #define HEADER_HPP_

    #if (baseAddress != 0) && (baseAddress != 0x20)
        #error "baseAddress has to either be 0 or 0x20"
    /*
     *
     */

    #endif
/*
 *
 */
#endif

//
```

With nothing after the last `#endif` statement
```c++
#ifndef HEADER_HPP_
#define HEADER_HPP_

#if (baseAddress != 0) && (baseAddress != 0x20)
    #error "baseAddress has to either be 0 or 0x20"
    /*
     *
     */

#endif
/*
 *
 */
#endif

```

**Comment by Wirena** [comment]
@ericwomer 
Comments after the last #endif make clang-format think it's not a header guard, I guess. So, is the issue resolved?

**Comment by ericwomer** [comment]
@Wirena Yeah, the issue can be marked as resolved.
