### ISSUE TITLE
`TabWidth` fails to apply properly to the preview when changed from default

### ISSUE THREAD

**Issue by DragRedSim** [Wirena/clang-format-configurator-v2#59]
I'm working on setting up a personal clang-format, and I'd like to use tab indents with a width of 2 characters. However, this does not apply correctly into the preview pane, making it difficult to predict how this is applied.
Clang-format will calculate the correct number of tabs to apply as an indent for the specified `TabWidth`, however the preview pane does not update its internal tab width, which remains at four characters. Therefore, anything that is tab-indented will show in the preview as being indented the right number of tab stops, but with double the width of what it should resolve to.
I was able to manually override the Ace Editor's setting using the JS console, by executing the following code: `ace.edit("Ace editor").session.setOption("tabSize", 2);`

**Comment by Wirena** [comment]
@DragRedSim thanks for your bug report, I'll fix this

**Comment by Wirena** [comment]
@DragRedSim I fixed the issue, could you double check that current behavior is correct, please?

**Comment by DragRedSim** [comment]
> @DragRedSim I fixed the issue, could you double check that current behavior is correct, please?

Looks good to me!
