### ISSUE TITLE
Provide a tab with the raw `.clang-format` contents instead of Upload/Download

### ISSUE THREAD

**Issue by mrexodia** [Wirena/clang-format-configurator-v2#7]
Currently you have to constantly upload/download to try out a few changes. It would be more convenient if there was a tab/button to switch between the UI and the raw file so you can simply copy/paste

**Comment by Wirena** [comment]
Nice feature, i think i'll implement it in the near future

**Comment by Wirena** [comment]
@mrexodia well, better late than never
